### ISSUE TITLE
FAssetRegistryModule::AssetCreated  crashes in Standalone mode

### ISSUE THREAD

**Issue by jimver04** [specklesystems/speckle-unreal#34]
The "#if WITH_EDITOR" is a macro that does not recognize if the project is running on Standalone. 

Fix: Replace 

```
#if WITH_EDITOR
     FAssetRegistryModule::AssetCreated(DynMaterial);
#endif
```

with this

```
if (GetWorld()->WorldType == EWorldType::PIE)
{
    FAssetRegistryModule::AssetCreated(DynMaterial);
}
```

**Comment by JR-Morgan** [comment]
Could you give us a little more details about your crash? I.e when it happens (I assume standalone build), and which mesh actor you are using (SpeckleUnrealStaticMesh or SpeckleUnrealProceduralMesh) ?

**Comment by JR-Morgan** [comment]
@jimver04 Sorry to reopen this again,
In case you missed it, I implemented your suggestion.

However I will need to change it to
```cpp
const auto WorldType = GetWorld()->WorldType;
if (WorldType == EWorldType::PIE || WorldType  == EWorldType::Editor )
{
    FAssetRegistryModule::AssetCreated(DynMaterial);
}
```

Because we need to create assets in Editor mode.

But this has got me thinking, do we really want to create assets on `PIE`? or should it just be in [`EWorldType::Editor`](https://docs.unrealengine.com/4.27/en-US/API/Runtime/Engine/Engine/EWorldType__Type/)

I'm thinking that most users would expect PIE to behave more like a standalone build and not create asset files.
Very few other things that happen in PIE have persistant effects to the Editor.
I propose that creating asset files should only be for non play (editor) mode, i.e

```cpp
if (GetWorld()->WorldType  == EWorldType::Editor )
{
    FAssetRegistryModule::AssetCreated(DynMaterial);
}
```
